#!/bin/bash
DIR=${PWD}
BASEDIR=$(dirname $0)
SUBJECT="Subject Name"
TITLE="Title"
GROUP="Group Name"
NAMES="Names"

while getopts ":s:n:t:g:d:" opt; do
  case $opt in
    s)
      SUBJECT=$OPTARG
      ;;
    n)
      NAMES=$OPTARG
      ;;
    t)
      TITLE=$OPTARG
      ;;
    g)
      GROUP=$OPTARG
      ;;
    d)
      NAMES=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

cd "$BASEDIR"

echo '\documentclass[a4paper,article]{memoir}
\usepackage[danish,english]{babel}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{wallpaper}
\usepackage{palatino}
\begin{document}
\thispagestyle{empty}
\ULCornerWallPaper{1}{natbio-farve.pdf}
\ULCornerWallPaper{1}{natbio-farve-grid-full.pdf}
\ULCornerWallPaper{1}{diku-en.pdf}
\begin{adjustwidth}{-3cm}{-1.5cm}
\vspace*{1cm}' >frontpage.tex

echo "\textbf{\Huge $SUBJECT }\\\ " >>frontpage.tex
echo '\vspace*{2.5cm} \\ ' >>frontpage.tex
echo "\textbf{\Huge $TITLE } \\\ " >>frontpage.tex
echo '\vspace*{.1cm} \\ ' >>frontpage.tex
echo "{\huge $GROUP } \\\ " >>frontpage.tex
echo '\begin{tabbing}' >>frontpage.tex
echo "$NAMES ~~ \= " >>frontpage.tex

echo '\\[12.6cm]
\textbf{\Large } \\
\> \texttt{} \\
\end{tabbing}
\end{adjustwidth}
\ClearWallPaper
\end{document}' >> frontpage.tex

pdflatex frontpage.tex
rm frontpage.tex
rm frontpage.aux
rm frontpage.log
if [ "$DIR" = "$BASEDIR" ]; then
    mv ./frontpage.pdf "${DIR}"/frontpage.pdf
fi
cd ${DIR}
